### ISSUE TITLE
"Next page" button not working

### ISSUE THREAD

**Issue by JesusValera** [TypedDevs/bashunit#110]
## 📚 Description

Being on the [Getting Started](https://bashunit.typeddevs.com/getting-started.html) page, when you scroll down to the bottom and try to go to `next page`, instead of going to `Assertions` page, you go to `#installation`, which is a subsection from `getting started page`.

<img width="1438" alt="image" src="https://github.com/TypedDevs/bashunit/assets/6381924/8b1ff3ae-ce57-4645-828e-bac0e767aeda">

**Comment by Tito-Kati** [comment]
Uhm... it seems that VitePess doesn't expect us to put links in the sidebar to different parts of the same page. I'll take a look to see if it can be fixed.

I understand that the most desirable decision is to take you to the next page (Assertions in this case), but if that's not possible, what would be more desirable?
a) Remove the links to the Installation and Usage subsections from the sidebar
b) Remove the 'next page' section from the footer

**Comment by Chemaclass** [comment]
I would vote for `b) Remove the 'next page' section from the footer`
