### ISSUE TITLE
Add SIMPLE_OUTPUT env var

### ISSUE THREAD

**Issue by Chemaclass** [TypedDevs/bashunit#142]
## Status quo

Currently, you can use the option `-s|--simple` when running `./bashunit` to display dots instead of the test names. 

## Expected

Allow defining `SIMPLE_OUTPUT` in the .env with a default:false, 
but when set true then it will have the same behaviour as using `--simple` option

### Consider

The .env configuration must be overwritten by the command configuration.
That is, if in the .env it is disabled, but --simple is used, then it should be displayed with simple mode.

**Comment by Tito-Kati** [comment]
The .env configuration must be overwritten by the command configuration.

That is, if in the .env it is disabled, but --simple is used, then it should be displayed with simple mode.

**Comment by Tito-Kati** [comment]
The .env configuration must be overwritten by the command configuration.

That is, if in the .env it is disabled, but --simple is used, then it should be displayed with simple mode.
