### ISSUE TITLE
Add --upgrade option

### ISSUE THREAD

**Issue by Chemaclass** [TypedDevs/bashunit#143]
## Expected

Add a new option `--upgrade` that will upgrade bashunit to the latest release.

#### Using latest branch

- You could think about using the `latest` branch and build bashunit from it. 
  - The `latest` branch will/should always point to the latest stable release

#### Using latest release

You could consider using the latest release: https://github.com/TypedDevs/bashunit/releases/latest 
  - which will point to the release page, and download from there the [bashunit file](https://github.com/TypedDevs/bashunit/releases/download/0.7.0/bashunit)

**Comment by gpuligundla** [comment]
Hi @Chemaclass, can I work on this?

**Comment by Chemaclass** [comment]
For sure, @gpuligundla. Feel free to work on this and create a PR 👍🏼

**Comment by Tito-Kati** [comment]
Of course @gpuligundla , I'll assign you the issue. If you need help with anything or run into any problems, let us know.

Thanks you!
