### ISSUE TITLE
Add option --stop-on-failure

### ISSUE THREAD

**Issue by Chemaclass** [TypedDevs/bashunit#144]
## Currently

If a test fails, the runner will continue until finalising all tests

## Expected

Add a new option `--stop-on-failure` that will force to stop the runner right after encountering one failing test.

> Inspired by PHPUnit: https://docs.phpunit.de/en/10.3/configuration.html#the-stoponfailure-attribute

### HINT

1. Look at how the _SIMPLE_OUTPUT is implemented
2. Look at the existing command options in the entry point of bashunit: https://github.com/TypedDevs/bashunit/blob/main/bashunit 

```bash
# for example:
while [[ $# -gt 0 ]]; do
  argument="$1"
  case $argument in
    ...
    --stop-on-failure)      
      _STOP_ON_FAILURE=true
      shift
      ;;
    ...
  esac
done
```

Then, we could check that global variable inside the `function console_results::print_failed_test()` and if it's true then force an `exit 1`

**Comment by Franqsanz** [comment]
Hello, in which file should it go?

**Comment by Chemaclass** [comment]
Hi, @Franqsanz ! I added some HINTS in the issue description. Let us know if you need more help

**Comment by Franqsanz** [comment]
I ask you @Chemaclass, this should be like this ?

```shell
_FILTER=""
_SIMPLE_OUTPUT=false
_STOP_ON_FAILURE=false
_FILES=()

while [[[ $# -gt 0 ]]; do
  argument="$1"
  case $argument in
    -f|--filter)
      _FILTER="$2"
      shift
      shift
      ;;
    -s|--simple)
      _SIMPLE_OUTPUT=true
      shift
      ;;
    -v|--version)
      console_header::print_version
      trap '' EXIT && exit 0
      ;;
    --stop-on-failure)
      _STOP_ON_FAILURE=true
      shift
      ;;
    *)
      while IFS='' read -r line; do
        _FILES+=("$line");
      done < <(helpers::find_files_recursive "$argument")
      shift
      ;;
  esac
done

console_header::print_version_with_env
runner::load_test_files "$_FILTER" "${_FILES[@]}"

exit 0
```

I'm having trouble understanding it at the moment

**Comment by Chemaclass** [comment]
Yes, that's the first part. Now you need to use that variable inside the function responsible to render the failing tests

**Comment by Franqsanz** [comment]
Hi, I'm kind of lost, it would be something like this what is missing? 

```shell
if [ "$_STOP_ON_FAILURE" = true ]; then
  console_results::print_failed_test
fi
```

I'm sure it's simple the missing part but I have no shell experience and it's hard for me to understand it. 😅

**Comment by Franqsanz** [comment]
This would look something like this ?

```shell
if [[ $test_result_code -ne 0 ]]; then
   state::add_tests_failed
   console_results::print_error_test "$function_name" "$test_result_code"

   if [ "$_STOP_ON_FAILURE" = true ]; then
     console_results::print_failed_test "$function_name" "$test_result_code"
     exit 1
   fi

   return
fi
```
If this is not the case, you can assign it to someone else, I don't want to take more time, anyway thanks for the help.

**Comment by Chemaclass** [comment]
Done https://github.com/TypedDevs/bashunit/pull/184
