### ISSUE TITLE
Make the test dir entrypoint optional

### ISSUE THREAD

**Issue by Chemaclass** [TypedDevs/bashunit#152]
## Current

Right now, you have to pass the directory|file of the test(s) that you want to run. Eg:
```bash
./basunit tests
```

## Expected

Allow defining the directory entry point as `.env` global variable. This will be the directory that will be taken if no directory or file was specified when running `.bashunit`. Eg:
```env
DEFAULT_PATH=tests
```

> DEFAULT_PATH is just a suggestion. Feel free to think about another better naming.

**Comment by Miki471151** [comment]
Hello. I'd like to work on this issue. Please assign it to me.

**Comment by Chemaclass** [comment]
@Miki471151, feel free to create a PR

**Comment by Chemaclass** [comment]
@Miki471151, are you still interested on working on this feature?

**Comment by Miki471151** [comment]
Yes. Im working on it.

**Comment by Chemaclass** [comment]
@Miki471151, consider creating a draft PR to share the current progress so we can give you hints and ideas if needed. This helps to create transparency 🧠
