### ISSUE TITLE
Improvements in simple output

### ISSUE THREAD

**Issue by antonio-gg-dev** [TypedDevs/bashunit#170]
Some improvements need to be made to the simple output, the one currently implemented is a very simple first iteration but requires a few enhancements to match the verbose output.

Currently, the simple output only prints a dot for each test, interleaving error, skip, and todo messages among the dots, giving a somewhat strange feel.

The goal we would want to achieve would be:
1. Not to print only dots, but also f (in red for failed), s (in yellow for skipped), and i (in blue for incomplete) whenever a test is found that does not pass for any of these reasons.
2. The messages from these 3 types of tests should not be printed until the end, that is, the dots (with the respective letters in the cases we mentioned) will be printed first, and once finished, all messages will be printed.

**Comment by Chemaclass** [comment]
Done https://github.com/TypedDevs/bashunit/pull/342
