### ISSUE TITLE
Add cookies pop-up

### ISSUE THREAD

**Issue by JesusValera** [TypedDevs/bashunit#200]
We have to show a modal where we tell to users we store some minimal information from them, and add the options to confirm/deny it, do we track something with Google Analytics, Cloudflare or other? @Tito-Kati

**Comment by Tito-Kati** [comment]
@JesusValera We have server-side analytics with Cloudflare, so we don't need to put one of those annoying cookie modals since the information we track from our users is 100% anonymous. 👍🏻 🌈
