### ISSUE TITLE
The providers generate a poor dev-friendly output

### ISSUE THREAD

**Issue by antonio-gg-dev** [TypedDevs/bashunit#203]
When you use providers, the name of the test is printed over and over without indicating with which argument of the provider it is being executed, this is unfriendly since while you are developing you do not know if the provider is really working as we expect, or if the tests are being executed passing the arguments we want.

![imagen](https://github.com/TypedDevs/bashunit/assets/13595197/700a3752-bfa5-4699-8fd7-6bfde4d9f2df)

For this, I think it would be good to make the following changes:

### Milestone 1:

> Done: https://github.com/TypedDevs/bashunit/pull/204

Print, in parentheses to the right of the name of the test, the arguments with which it is being provided.
```
✓ Passed: Returns fizz when multiple of 3 given (3)
✓ Passed: Returns fizz when multiple of 3 given (6)
✓ Passed: Returns fizz when multiple of 5 given (5)
✓ Passed: Returns fizz when multiple of 5 given (10)
```

### Milestone 2:

Moved to another issue: https://github.com/TypedDevs/bashunit/issues/252

**Comment by Chemaclass** [comment]
Milestone 1 done. 
Milestone 2 moved to https://github.com/TypedDevs/bashunit/issues/252
