### ISSUE TITLE
Remove downtime on install latest

### ISSUE THREAD

**Issue by Chemaclass** [TypedDevs/bashunit#225]
## Current

When creating a new release, we have to change the release version in many files (see `.github/RELEASE.md`). However, currently the `install.sh` is one of them and that's creating a downtime when we are creating a new release - during the time when this change it's pushed and the actual new release is created, the installer tool wont work.

## Expected

Instead of using a hardcoded version on `install.sh`, we should get the latest stable version.
In this [PR](https://github.com/TypedDevs/bashunit/pull/222/files), we introduced `get_latest_tag()` and we could use it on `install.sh` script instead of a hardcoded version.

```bash
function helpers::get_latest_tag() {
  git ls-remote --tags "$BASHUNIT_GIT_REPO" |
    awk '{print $2}' |
    sed 's|^refs/tags/||' |
    sort -V |
    tail -n 1
}
```

**Comment by gpuligundla** [comment]
Can i work on it ?

**Comment by Tito-Kati** [comment]
Great to see you back here again, @gpuligundla !

Of course, would you mind waiting a bit before starting it? We want to make some small changes to your last contribution that might affect the way to solve this issue.

When we make the changes, we'll let you know so that you can take a look at them too and then you can start this one. Meanwhile, I'll go ahead and assign it to you. 😊

**Comment by Tito-Kati** [comment]
@gpuligundla we already merged #227 so you can start this issue when you want 😃

**Comment by Chemaclass** [comment]
Actually, I think we should copy/paste the function `helpers::get_latest_tag()` function entirely in the install.sh script, because it must be a fully independent script, as it it what the users will download (as single script) to install bashunit. So we cannot source/load other scripts within the installer.

**Comment by maheshmeleti** [comment]
I would like to work on this, please assign this issue to me.

**Comment by Chemaclass** [comment]
@maheshmeleti let us know if you need help with this

**Comment by maheshmeleti** [comment]
@Chemaclass im still working on it
