### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by khru** [TypedDevs/bashunit#25]
Create a file where we allow the users to choose how they want to configure their library, Examples:

- PHPUnit: https://phpunit.de/manual/6.5/en/appendixes.configuration.html
- Jest: https://jestjs.io/docs/configuration

**Comment by Tito-Kati** [comment]
Isn't this the .env we already have? Could we close this issue?

I've created a task to document its usage #87.

**Comment by khru** [comment]
Now It is, but the .env file it's 'on our repo' but It should be on Who uses the library

**Comment by Tito-Kati** [comment]
It's the configuration that our repo uses to test itself, right? So indirectly we are creating this system out of necessity. Perhaps what remains to be implemented is for the library to take the .env it finds at the root of our users' project? But the system should be the same, right?

Perhaps I'm unintentionally mixing things up.

**Comment by JesusValera** [comment]
Which configuration do we have currently?

As far as I know, there is only `PARALLEL_TEST=`, isn't it?
Do we plan to add new values?

Also, we should add a new section on the web with this info 🤔

**Comment by Tito-Kati** [comment]
> Which configuration do we have currently?
> 
> As far as I know, there is only `PARALLEL_TEST=`, isn't it? Do we plan to add new values?
> 
> Also, we should add a new section on the web with this info 🤔

We actually don't have PARALLEL_TEST feature right now, it was removed in the last version.

Even so, I think we could add some configuration options that might be of interest... like being able to define a default directory for tests, so when you run the script without specifying the tests, it automatically picks it up from there.

Regarding adding a section to the documentation on how to configure the library, there's already an issue created about it #87 , but of course, we don't have anything to configure right now.

**Comment by Tito-Kati** [comment]
Bump this issue, so now we have SHOW_HEADER and HEADER_ASCII_ART, and can add more like --simple

**Comment by Chemaclass** [comment]
What about creating a new page in the docs to explain in detail about those settings, @Tito-Kati

**Comment by Tito-Kati** [comment]
@Chemaclass #87 👍🏻

**Comment by Chemaclass** [comment]
I think we can close this one, as it was already done.
