### ISSUE TITLE
Display total number tests

### ISSUE THREAD

**Issue by Chemaclass** [TypedDevs/bashunit#291]
## Current

When running `./bashunit`, at the end, we know the total of tests and assertions:

![Screenshot 2024-07-14 at 00 51 01](https://github.com/user-attachments/assets/3eaa1c04-9616-467b-bced-1e87eae67b53)

## Expected

The task is to calculate these numbers  (total of tests and assertions) in advance, and display them at the very beginning to have early feedback of how many of them will be there.

## Observation

These numbers are currently calculated on the fly, as we go. There might be a way to search and find by pattern these numbers, let's assume the following:
- **tests**: are all functions starting with `test` in all testing scripts
- **assertions**: functions being called that start with `assert` inside each test

## HINT
Something like this might help
```bash
function helpers::find_test_functions() {
    local dir=${1:-tests}
    grep -r -E '^\s*function\s+test' "$dir" --include=\*.sh 2>/dev/null \
      | wc -l \
      | xargs
}
```

**Comment by staabm** [comment]
Calculating assertions count for a test with dataprovider(s) is not possible, I guess?

**Comment by Chemaclass** [comment]
@staabm, good point. I think it would be possible but not as straight forward. We could start having this logic as first PR for the tests only and we will figure out later the assertions.

**Comment by Chemaclass** [comment]
Related: add a loader bar at the bottom while runing the tests

I found this great example here https://github.com/kndndrj/shload by @kndndrj 
I will work on add some tests and try to integrate something similar in our bashunit 🧠
