### ISSUE TITLE
Filter not working with test_ prefix

### ISSUE THREAD

**Issue by Chemaclass** [TypedDevs/bashunit#299]
| Q                | A                       |
|------------------|-------------------------|
| OS               | macOS / Linux / Windows |
| Shell            | sh / bash / ...         |
| bashunit version | 0.14                   |

#### Current behavior

The [filter](https://bashunit.typeddevs.com/command-line#filter) is not working when using full test name (with `test_` prefix)

![Screenshot 2024-07-17 at 09 23 29](https://github.com/user-attachments/assets/01578b93-11d3-4c0a-a1bd-ae1f4865ca25)

#### How to reproduce

```bash
./bashunit tests/unit/state_test.sh -f test_calculate_total_assertions
```

#### Expected behavior

```bash
./bashunit tests/unit/state_test.sh -f calculate_total_assertions
# should work as
./bashunit tests/unit/state_test.sh -f test_calculate_total_assertions
```

## HINT

1. A test:
```bash
# tests/unit/helpers_test.sh

# below: test_get_functions_to_run_with_filter_should_return_matching_functions

function test_get_functions_to_run_with_filter_but_complete_function_name() {
  local functions=("prefix_function1" "prefix_function2" "other_function" "prefix_function3")

  assert_equals "prefix_function2" "$(helper::get_functions_to_run "prefix" "prefix_function2" "${functions[*]}")"
}
```

2. The code:
Inside `helper::get_functions_to_run:61` add an OR condition to check that the fn is equal to the filter regex only without the prefix. E.g.:
```bash
# src/helpers.sh

|| $fn == ${filter}* 
```

**Comment by ishuar** [comment]
Thank you @Chemaclass  for the hint 🙌
