### ISSUE TITLE
the global value in set_up can not be used when using multi_invoker  

### ISSUE THREAD

**Issue by shalk** [TypedDevs/bashunit#308]
| Q                | A                       |
|------------------|-------------------------|
| OS               | macOS  |
| Shell            |bash      |
| bashunit version |0.14.0             |

#### Summary

when using multi_invoker , the global value in set_up can not be used.

#### How to reproduce

```
#!/bin/bash

function set_up() {
  AAA="aaa"
}

function invoker_with_args() {
  test_hi "aaa"
  test_hi "bbb"
  test_hi "ccc"
}

# multi_invoker invoker_with_args
function test_hi() {
  assert_equals "aaa" "${AAA}"
}

```
```
 test git:(master) ✗ ./lib/bashunit ./tests 
bashunit - 0.14.0
Running ./tests/example1_test.sh
✗ Failed: Hi
    Expected 'aaa'
    but got ''
✗ Failed: Hi
    Expected 'aaa'
    but got ''
✗ Failed: Hi
    Expected 'aaa'
    but got ''

Tests:      0 failed, 0 total
Assertions: 3 failed, 3 total

 No tests found 
Time taken: 71 ms
```

**Comment by Chemaclass** [comment]
Thanks for reporting, @shalk! I am working on this.

**Comment by Chemaclass** [comment]
`Multi-invokers` will be removed in the next release, in favor of `data providers`. 
Here you can see an example of how to use it (very similar from your example):

![Screenshot 2024-08-31 at 23 08 46](https://github.com/user-attachments/assets/1c7b1e16-bdc5-4c2c-9499-f10609cfccfd)

### Major changes that you might be interested

For the upcoming `0.15` release - in the coming days :

- `data_provider` will support multiple arguments (currently on 0.14 supports only one arg)
- `set_up()` and similar functions will work as expected with `data providers`
- `multi_invoker` will be removed in favor of `data providers`
