### ISSUE TITLE
Test with syntax error should fail

### ISSUE THREAD

**Issue by mkonig** [TypedDevs/bashunit#309]
| Q                | A                       |
|------------------|-------------------------|
| OS               | Linux |
| Shell            | bash         |
| bashunit version | 0.14.0                  |

#### Summary

Tests that have syntax or execution errors should fail with the corresponding output.

Example:
```
function test_i_should_fail() {
    expected_count=1
    uiaeae
    count=$(count_charging_stations "$something")
    assert_equals "$expected_count" "$expected_count"
}
```

This test passes even though it contains code that is wrong and a function
that does not even exist.

#### Current behavior

Test passes even thought the code would never be able to run at all.

#### How to reproduce

Print the stderr of bash.

#### Expected behavior

Test should fail and tell me what was wrong. It would help a lot when doing TDD.

**Comment by Chemaclass** [comment]
This is already in the beta https://bashunit.typeddevs.com/installation#define-custom-tag-and-folder
and it will be in the next stable version. Thanks for the issue :)
![Screenshot 2024-09-13 at 22 36 47](https://github.com/user-attachments/assets/6d6a0d14-d3ca-4535-bf6b-0bd1c83b42fb)
