### ISSUE TITLE
assert files are equal

### ISSUE THREAD

**Issue by staabm** [TypedDevs/bashunit#322]
I wonder whether there is a assertion which allows me to compare a file which contains the expected content with one containing the actual content?

**Comment by Chemaclass** [comment]
We don't have that right now, but it should be easy to include! Very nice idea.
If you want to do it: check the existing https://bashunit.typeddevs.com/assertions#assert-is-file works, and you can implement a similar for assert_file_equals or similar. Otherwise, I can work on it this weekend
