### ISSUE TITLE
`assert_not_same` is not implemented

### ISSUE THREAD

**Issue by smeghead** [TypedDevs/bashunit#372]
| Q                | A                       |
|------------------|-------------------------|
| OS               | macOS / Linux / Windows |
| Shell            | bash          |
| bashunit version | 0.17.0                   |

#### Summary

The `assert_not_same` function described in the documentation seemed to be unimplemented.

https://bashunit.typeddevs.com/assertions#assert-not-same

`assert_not_same` is not implemented

#### Current behavior

When I try to use `assert_not_same`, I get an error message that the function does not exist.

#### How to reproduce

```bash
# ./bashunit -a assert_not_same "123" "123"
Function assert_not_same does not exist.
```

#### Expected behavior

We expect the assertion to be made correctly using `assert_not_same`.

#### Todo

https://x.com/Chemaclass/status/1844765933618753646

- rename assert_not_equals to assert_not_same (and all its usages)
- add a new assert_not_equals (look at assert_equals and use opposite condition)
- make sure there are unit tests for this new assert_not_equals

**Comment by Chemaclass** [comment]
Do you want to try this out, @smeghead ?

**Comment by smeghead** [comment]
@Chemaclass 
Yes, I want to try out.
And, I need to learn about bashunit testing.
