### ISSUE TITLE
Glitch in the name rendered in the results, from  test_something() 

### ISSUE THREAD

**Issue by AndiKod** [TypedDevs/bashunit#387]
| Q                | A                       |
|------------------|-------------------------|
| OS               | Linux Mint WSL |
| Shell            | bash in WezTerm      |
| bashunit version | 0.18.0                   |

#### Summary

Not ground breaking, but it seems to be a glitch in the rendering function that transforms things like `function test_something_exists() {}` into `Passed: Something exists`

#### Current behavior

I have three simple functions: test_bin_dir_exists(), test_lib_dir_exists() and test_tests_dir_exists().
The last one is rendered as: `Passed: S dir exists`. It looks like the regular expression made to remove the first 'test' string worked too on the second one. 

#### How to reproduce

Well. Create a `function test_tests_dir_exists()` and see how it renders.

#### Expected behavior

It's supposed to render as `Passed:  Tests dir exists.`

*Note: I made it to work as expected by capitalizing the T in `function test_Tests_dir_exists()`, so my bet is on some regEx. It worked too with a double underscore like `test__tests` but it rendered an initial space and no capitalization.*

**Comment by Chemaclass** [comment]
Awesome finding! Thanks, @AndiKod!

**Comment by AndiKod** [comment]
Thank you and the team for the tool. Just discovered BashUnit and it's already a part of my Bash companion project I have in the making. 

If I stumble on something else, I'll come back here.

**Comment by Chemaclass** [comment]
The fix is merged on main, and you can try it yourself with the beta version (which build the code from main)
```bash
curl -s https://bashunit.typeddevs.com/install.sh | bash -s lib beta
```
Docs: https://bashunit.typeddevs.com/installation#define-custom-tag-and-folder

**Comment by AndiKod** [comment]
Works like a charm :)
