### ISSUE TITLE
Error on count of assertions and failures

### ISSUE THREAD

**Issue by khru** [TypedDevs/bashunit#62]
#### Summary

I have created a test that should fail due to human error and in the error list, I see the error but it is not being counted in the final counter.

#### Current behavior

Full example:
![bug_assert_equals_and_counters](https://github.com/Chemaclass/bashunit/assets/6353105/b773900f-e41c-445e-8b71-d28b28bcf4ed)

#### How to reproduce

If you create a test like
```bash
function test_bug_on_assert_equals() {
  function fake_function() {
    return 1
  }
  assertEquals\
  "$SUCCESSFUL_EMPTY_MESSAGE" "$(assertSuccessfulCode "$(fake_function)")"

  assertGeneralError "$(fake_function)"
}
```

The output shows:
```
Running tests/unit/assert_test.sh
✗ Failed: Bug on assert equals
    Expected ''
    but got '✗ Failed: Bug on assert equals
    Expected '1'
    to be exactly '0''
```
![image](https://github.com/Chemaclass/bashunit/assets/6353105/15598a4f-117c-4727-889a-3b17aa64bc75)

but the list of test failing and assertions fail it's not increasing

![image](https://github.com/Chemaclass/bashunit/assets/6353105/c513cb38-2db9-46fb-a759-a378242b7e90)

#### Expected behavior

Count the real number of assertions

This issue could be related to: https://github.com/Chemaclass/bashunit/issues/50

**Comment by khru** [comment]
I would revert the solution we applied in this fix and just find a way for the counter to show that it has failed, since for me that is the behavior it should have.

**Comment by Tito-Kati** [comment]
In a conversation with @khru, we saw that this is currently working as expected, at least for now. I'm closing this issue.
